name: CI

on:
  push:
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'renovate.json'
      - '.gitignore'
  pull_request:
  workflow_dispatch:

jobs:
  Build-and-Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows] # todo, add mac and windows ?
        jvm_version: # Update using LTSs and latest
          # - adopt@1.8,
          - adopt@1.11
          - openjdk@1.17
    runs-on: ${{ matrix.os }}-latest
    concurrency:
      group: ${{ github.workflow }}-build-${{ matrix.os }}-${{ matrix.jvm_version }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Setup Scala and JDK
        with:
          java-version: ${{ matrix.jvm_version }}
        uses: olafurpg/setup-scala@v14
      - name: Sbt run tests
        shell: bash # for windows
        run: sbt test